<?php

/**
 * BaseBookableResource
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property integer $bookableId
 * @property integer $empNumber
 * @property smallint $isActive
 * @property string $bookableColor
 * @property Employee $Employee
 * @property Booking $Booking
 *
 * @method integer          getBookableId()     Returns the current record's "bookableId" value
 * @method integer          getEmpNumber()      Returns the current record's "empNumber" value
 * @method smallint         getIsActive()       Returns the current record's "isActive" value
 * @method string           getBookableColor()  Returns the current record's "bookableColor" value
 * @method Employee         getEmployee()       Returns the current record's "Employee" value
 * @method Booking          getBooking()        Returns the current record's "Booking" value
 * @method BookableResource setBookableId()     Sets the current record's "bookableId" value
 * @method BookableResource setEmpNumber()      Sets the current record's "empNumber" value
 * @method BookableResource setIsActive()       Sets the current record's "isActive" value
 * @method BookableResource setBookableColor()  Sets the current record's "bookableColor" value
 * @method BookableResource setEmployee()       Sets the current record's "Employee" value
 * @method BookableResource setBooking()        Sets the current record's "Booking" value
 *
 * @package    orangehrm
 * @subpackage model\booking\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBookableResource extends sfDoctrineRecord {

  public function setTableDefinition() {
    $this->setTableName('hs_hr_bookable_resource');
    $this->hasColumn('bookable_id as bookableId', 'integer', 7, array(
      'type' => 'integer',
      'primary' => true,
      'length' => 7,
    ));
    $this->hasColumn('emp_number as empNumber', 'integer', 7, array(
      'type' => 'integer',
      'notnull' => true,
      'length' => 7,
    ));
    $this->hasColumn('is_active as isActive', 'smallint', null, array(
      'type' => 'smallint',
      'default' => '0',
    ));
    $this->hasColumn('bookable_color as bookableColor', 'string', 8, array(
      'type' => 'string',
      'notnull' => true,
      'default' => '#000',
      'length' => 8,
    ));
  }

  public function setUp() {
    parent::setUp();
    $this->hasOne('Employee', array(
      'local' => 'emp_number',
      'foreign' => 'emp_number'));

    $this->hasOne('Booking', array(
      'local' => 'bookable_id',
      'foreign' => 'bookableId'));
  }

}
