<?php

/**
 * BaseBooking
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $bookingId
 * @property integer $bookableId
 * @property integer $customerId
 * @property integer $projectId
 * @property float $duration
 * @property date $startDate
 * @property date $endDate
 * @property time $startTime
 * @property time $endTime
 * @property string $bookingColor
 * @property clob $availableOn
 * @property BookableResource $BookableResource
 * @property Customer $Customer
 * @property Project $Project
 * 
 * @method integer          getBookingId()               Returns the current record's "bookingId" value
 * @method integer          getBookableId()              Returns the current record's "bookableId" value
 * @method integer          getCustomerId()              Returns the current record's "customerId" value
 * @method integer          getProjectId()               Returns the current record's "projectId" value
 * @method float            getDuration()                Returns the current record's "duration" value
 * @method date             getStartDate()               Returns the current record's "startDate" value
 * @method date             getEndDate()                 Returns the current record's "endDate" value
 * @method time             getStartTime()               Returns the current record's "startTime" value
 * @method time             getEndTime()                 Returns the current record's "endTime" value
 * @method string           getBookingColor()            Returns the current record's "bookingColor" value
 * @method clob             getAvailableOn()             Returns the current record's "availableOn" value
 * @method BookableResource getBookableResource()        Returns the current record's "BookableResource" value
 * @method Customer         getCustomer()                Returns the current record's "Customer" value
 * @method Project          getProject()                 Returns the current record's "Project" value
 * @method Booking          setBookingId()               Sets the current record's "bookingId" value
 * @method Booking          setBookableId()              Sets the current record's "bookableId" value
 * @method Booking          setCustomerId()              Sets the current record's "customerId" value
 * @method Booking          setProjectId()               Sets the current record's "projectId" value
 * @method Booking          setDuration()                Sets the current record's "duration" value
 * @method Booking          setStartDate()               Sets the current record's "startDate" value
 * @method Booking          setEndDate()                 Sets the current record's "endDate" value
 * @method Booking          setStartTime()               Sets the current record's "startTime" value
 * @method Booking          setEndTime()                 Sets the current record's "endTime" value
 * @method Booking          setBookingColor()            Sets the current record's "bookingColor" value
 * @method Booking          setAvailableOn()             Sets the current record's "availableOn" value
 * @method Booking          setBookableResource()        Sets the current record's "BookableResource" value
 * @method Booking          setCustomer()                Sets the current record's "Customer" value
 * @method Booking          setProject()                 Sets the current record's "Project" value
 * 
 * @package    orangehrm
 * @subpackage model\booking\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBooking extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_booking');
        $this->hasColumn('booking_id as bookingId', 'integer', 7, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 7,
             ));
        $this->hasColumn('bookable_id as bookableId', 'integer', 7, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 7,
             ));
        $this->hasColumn('customer_id as customerId', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('project_id as projectId', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('duration as duration', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             ));
        $this->hasColumn('start_date as startDate', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('end_date as endDate', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('start_time as startTime', 'time', null, array(
             'type' => 'time',
             'notnull' => false,
             ));
        $this->hasColumn('end_time as endTime', 'time', null, array(
             'type' => 'time',
             'notnull' => false,
             ));
        $this->hasColumn('booking_color as bookingColor', 'string', 8, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '#000',
             'length' => 8,
             ));
        $this->hasColumn('available_on as availableOn', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BookableResource', array(
             'local' => 'bookableId',
             'foreign' => 'bookable_id'));

        $this->hasOne('Customer', array(
             'local' => 'customerId',
             'foreign' => 'customer_id'));

        $this->hasOne('Project', array(
             'local' => 'projectId',
             'foreign' => 'project_id'));
    }
}