<?php

/**
 * PluginBookableResourceTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginBookableResourceTable extends Doctrine_Table {

  /**
   * Returns an instance of this class.
   *
   * @return object PluginBookableResourceTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('PluginBookableResource');
  }

}
