<?php

/**
 * BookableResourceTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BookableResourceTable extends PluginBookableResourceTable {

  /**
   * Returns an instance of this class.
   *
   * @return object BookableResourceTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('BookableResource');
  }

}
