<?php

/**
 * BookingTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BookingTable extends PluginBookingTable {

  /**
   * Returns an instance of this class.
   *
   * @return object BookingTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('Booking');
  }

}
